# Generated by Django 2.0 on 2017-12-29 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Category'),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
