# Generated by Django 2.0 on 2017-12-29 00:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20171229_0308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticifation',
            new_name='Notification',
        ),
    ]
