# Generated by Django 2.0 on 2017-12-29 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20171229_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower_list',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(upload_to=''),
        ),
    ]
