# Generated by Django 2.0 on 2017-12-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20171229_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
