# Generated by Django 2.0 on 2018-01-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20171229_0523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date', 'ordering': ('-id',)},
        ),
    ]
