# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_textfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.AddField(
            model_name='entry',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
