# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0003_auto_20171120_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='hashtag',
            field=models.CharField(default='unidaylekesfet', max_length=50),
            preserve_default=False,
        ),
    ]
